# Generated by Django 3.1.1 on 2020-09-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_auto_20200920_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStat',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('game',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='games.game')),
            ],
        ),
    ]
