# Generated by Django 3.1.1 on 2020-09-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_playerstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWardStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wards_placed_1', models.IntegerField(default=0)),
                ('wards_placed_2', models.IntegerField(default=0)),
                ('wards_placed_3', models.IntegerField(default=0)),
                ('wards_placed_4', models.IntegerField(default=0)),
                ('wards_placed_5', models.IntegerField(default=0)),
                ('wards_destroyed_1', models.IntegerField(default=0)),
                ('wards_destroyed_2', models.IntegerField(default=0)),
                ('wards_destroyed_3', models.IntegerField(default=0)),
                ('wards_destroyed_4', models.IntegerField(default=0)),
                ('wards_destroyed_5', models.IntegerField(default=0)),
                ('control_wards_purchased_1', models.IntegerField(default=0)),
                ('control_wards_purchased_2', models.IntegerField(default=0)),
                ('control_wards_purchased_3', models.IntegerField(default=0)),
                ('control_wards_purchased_4', models.IntegerField(default=0)),
                ('control_wards_purchased_5', models.IntegerField(default=0)),
                ('game_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.gamestat')),
            ],
        ),
        migrations.CreateModel(
            name='GameIncomeStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_earned_1', models.IntegerField(default=0)),
                ('gold_earned_2', models.IntegerField(default=0)),
                ('gold_earned_3', models.IntegerField(default=0)),
                ('gold_earned_4', models.IntegerField(default=0)),
                ('gold_earned_5', models.IntegerField(default=0)),
                ('gold_spent_1', models.IntegerField(default=0)),
                ('gold_spent_2', models.IntegerField(default=0)),
                ('gold_spent_3', models.IntegerField(default=0)),
                ('gold_spent_4', models.IntegerField(default=0)),
                ('gold_spent_5', models.IntegerField(default=0)),
                ('minions_killed_1', models.IntegerField(default=0)),
                ('minions_killed_2', models.IntegerField(default=0)),
                ('minions_killed_3', models.IntegerField(default=0)),
                ('minions_killed_4', models.IntegerField(default=0)),
                ('minions_killed_5', models.IntegerField(default=0)),
                ('neutral_minions_killed_1', models.IntegerField(default=0)),
                ('neutral_minions_killed_2', models.IntegerField(default=0)),
                ('neutral_minions_killed_3', models.IntegerField(default=0)),
                ('neutral_minions_killed_4', models.IntegerField(default=0)),
                ('neutral_minions_killed_5', models.IntegerField(default=0)),
                ('game_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.gamestat')),
            ],
        ),
        migrations.CreateModel(
            name='GameDamageStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_damage_to_champs_1', models.IntegerField(default=0)),
                ('total_damage_to_champs_2', models.IntegerField(default=0)),
                ('total_damage_to_champs_3', models.IntegerField(default=0)),
                ('total_damage_to_champs_4', models.IntegerField(default=0)),
                ('total_damage_to_champs_5', models.IntegerField(default=0)),
                ('game_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.gamestat')),
            ],
        ),
        migrations.CreateModel(
            name='GameCombatStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills_1', models.IntegerField(default=0)),
                ('kills_2', models.IntegerField(default=0)),
                ('kills_3', models.IntegerField(default=0)),
                ('kills_4', models.IntegerField(default=0)),
                ('kills_5', models.IntegerField(default=0)),
                ('deaths_1', models.IntegerField(default=0)),
                ('deaths_2', models.IntegerField(default=0)),
                ('deaths_3', models.IntegerField(default=0)),
                ('deaths_4', models.IntegerField(default=0)),
                ('deaths_5', models.IntegerField(default=0)),
                ('assists_1', models.IntegerField(default=0)),
                ('assists_2', models.IntegerField(default=0)),
                ('assists_3', models.IntegerField(default=0)),
                ('assists_4', models.IntegerField(default=0)),
                ('assists_5', models.IntegerField(default=0)),
                ('largest_killing_spree_1', models.IntegerField(default=0)),
                ('largest_killing_spree_2', models.IntegerField(default=0)),
                ('largest_killing_spree_3', models.IntegerField(default=0)),
                ('largest_killing_spree_4', models.IntegerField(default=0)),
                ('largest_killing_spree_5', models.IntegerField(default=0)),
                ('largest_multi_kill_1', models.IntegerField(default=0)),
                ('largest_multi_kill_2', models.IntegerField(default=0)),
                ('largest_multi_kill_3', models.IntegerField(default=0)),
                ('largest_multi_kill_4', models.IntegerField(default=0)),
                ('largest_multi_kill_5', models.IntegerField(default=0)),
                ('first_blood', models.IntegerField(choices=[(0, 'Not on this team'), (1, 'Player 1'), (2, 'Player 2'), (3, 'Player 3'), (4, 'Player 4'), (5, 'Player 5')], default=0)),
                ('is_blue', models.BooleanField(default=True)),
                ('game_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.gamestat')),
            ],
        ),
    ]
