# Generated by Django 3.1.1 on 2020-09-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_gamecombatstat_gamedamagestat_gameincomestat_gamewardstat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecombatstat',
            old_name='is_blue',
            new_name='is_blue_side',
        ),
    ]
