# Generated by Django 3.1.1 on 2020-09-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200920_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedamagestat',
            name='is_blue_side',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gameincomestat',
            name='is_blue_side',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamewardstat',
            name='is_blue_side',
            field=models.BooleanField(default=True),
        ),
    ]
