# Generated by Django 3.1.1 on 2020-09-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameplayer",
            name="side",
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="blue_side",
            field=models.BooleanField(default=True),
        ),
    ]
