# Generated by Django 3.1.1 on 2020-09-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200920_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='pick_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
