# Generated by Django 3.1.1 on 2020-09-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200920_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamebanlist',
            name='ban_1',
        ),
        migrations.RemoveField(
            model_name='gamebanlist',
            name='ban_2',
        ),
        migrations.RemoveField(
            model_name='gamebanlist',
            name='ban_3',
        ),
        migrations.RemoveField(
            model_name='gamebanlist',
            name='ban_4',
        ),
        migrations.RemoveField(
            model_name='gamebanlist',
            name='ban_5',
        ),
    ]
