# Generated by Django 3.1.1 on 2020-09-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200920_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebanlist',
            name='ban_1',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='gamebanlist',
            name='ban_2',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='gamebanlist',
            name='ban_3',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='gamebanlist',
            name='ban_4',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='gamebanlist',
            name='ban_5',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
