# Generated by Django 3.1.1 on 2020-09-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('games', '0008_auto_20200920_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
    ]
