# Generated by Django 3.1.1 on 2020-09-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20200920_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamebanlist',
            old_name='blue_side',
            new_name='is_blue_side',
        ),
        migrations.RenameField(
            model_name='gamepicklist',
            old_name='blue_side',
            new_name='is_blue_side',
        ),
    ]
