# Generated by Django 3.1.1 on 2020-09-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20200920_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='blue_side',
            new_name='is_blue_side',
        ),
    ]
