# Generated by Django 3.1.1 on 2020-09-20 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('games', '0011_auto_20200920_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
    ]
